### ISSUE TITLE
Users must be able to be banned.

### ISSUE THREAD

**Issue by williams-jack** [ReviewSpot/reviewspot-node-server#2]
A moderator's powers are no good unless a user can be banned.

For the scope of this project we don't need to go as far as to implement IP banning. With that in mind, we will need to have a way to do it at the account level. Here's a basic overview of how it can be accomplished:

1. Add a `banned` boolean field to the User model. It's default is `false`.
2. Add a clause to the `login` function in the `auth-controller.js` module where if the user is banned, they cannot log into the app. The HTTP response will be a 4xx (authorization or forbidden; whichever is correct) code and a JSON object with an error message saying the user is banned.
3. Add a **moderator-only** function that takes in a `User`'s  `ObjectId` or their `username`, which the schema already guarantees is unique.

I still need to implement route security so some of this is dependent on that, but for now just wanted to document what this would all look like.

**Comment by Sohamkayal4103** [comment]
Can I work on this?

**Comment by williams-jack** [comment]
Hi Soham,

This is actually a project for a university course, so while I'd love to say yes I unfortunately can't receive external help. We have made this repository public so that the professor and TAs can keep track of it.

I will make a note in our READMEs though to save confusion in the future. Thank you so much for reaching out though!

Best,
Jackson

**Comment by Sohamkayal4103** [comment]
No problem. I am glad though to hear that this project is part of your university course. The place where I belong, that is Mumbai(India), all of this is not included in the University course and most of the people choose competitive programming over Software Development.

**Comment by wastech** [comment]
i would like to work on this project when everything is set up...
